module.exports = function(grunt, paths) {

  grunt.config.merge({
    clean: {
      options: {
        force: true
      }
    },
    concurrent: {
      options: {
        logConcurrentOutput: true
      }
    },
    includeSource: {
      options: {
        baseUrl: '/'
      }
    },
    less: {
      options: {
        strictMath: true,
        strictImports: true
      }
    },
    postcss: {
      options: {
        processors: [
          require('autoprefixer')({browsers: ['last 1 version']}),
          require('cssnano')
        ]
      }
    },
    jshint: {
      options: {
        jshintrc: '<%= paths.front_end_build %>/.jshintrc'
      }
    },
    ngconstant: {
      options: {
        wrap: '"use strict";\n// DO NOT EDIT THIS FILE, EDIT THE GRUNT TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n{%= __ngModule %}'
      }
    },
    watch: {
      configFiles: {
        files: [
          '<%= paths.front_end_build %>/Gruntfile.js',
          '<%= paths.front_end_build %>/paths.js',
          '<%= paths.tasks %>/*.js'
        ],
        options: {
          reload: true
        }
      }
    },
    browserSync: {
      options: {
        watchTask: true,
        proxy: 'localhost:8080',
        open: false,
        logFileChanges: false
      }
    }
  });

};
